// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6HZF5zYicxXTS7unI8yyZGPctGwQWel0',
    appId: '1:213140479137:web:7b1040ab0f5aefe00fe4e0',
    messagingSenderId: '213140479137',
    projectId: 'vibesfinalprojgym1',
    authDomain: 'vibesfinalprojgym1.firebaseapp.com',
    storageBucket: 'vibesfinalprojgym1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc3korPp5nLej5xZGBCrOmzd9VQ99RR6A',
    appId: '1:213140479137:android:16d67d263da631a30fe4e0',
    messagingSenderId: '213140479137',
    projectId: 'vibesfinalprojgym1',
    storageBucket: 'vibesfinalprojgym1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkiY3rrpL8VhafrQTFP1zQVJapyVKgaio',
    appId: '1:213140479137:ios:356b5c6cf3854e080fe4e0',
    messagingSenderId: '213140479137',
    projectId: 'vibesfinalprojgym1',
    storageBucket: 'vibesfinalprojgym1.appspot.com',
    iosClientId: '213140479137-vf7d662ip85ojqarbjgub97fkndc8mjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.yarab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkiY3rrpL8VhafrQTFP1zQVJapyVKgaio',
    appId: '1:213140479137:ios:21ad22c0a729d8fb0fe4e0',
    messagingSenderId: '213140479137',
    projectId: 'vibesfinalprojgym1',
    storageBucket: 'vibesfinalprojgym1.appspot.com',
    iosClientId: '213140479137-0sb0740m94t38jj9m3n4ioioetv6gmdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
